### ISSUE TITLE
Compilation error when using FML in single precision mode.

### ISSUE THREAD

**Issue by BartolomeoF** [HAWinther/FML#3]
When trying to compile the FML-COLA solver in single precision mode (SINGLE_PRECISION_FFTW option in the Makefile), the compilation fails with the error:

```
~/FML/FML/NBody/NBody.h:1598:80: error: no match for 'operator*' (operand types are 'std::complex<float>' and 'double') 
1598 |                     potential_real.set_fourier_from_index(fourier_index, value * norm_poisson_equation);
```

The error seems to be fixed by performing a static cast on the double variable `norm_poisson_equation` in [line 1598 of NBody.h](https://github.com/HAWinther/FML/blob/eba0865cd3e1cee7ba56b0b0fe03d4126d81cb76/FML/NBody/NBody.h#L1598) 
```
potential_real.set_fourier_from_index(fourier_index, value * static_cast<float>(norm_poisson_equation));
```
However this fix would be valid only when using the COLA solver in single precision mode, so a more general fix would be preferable.

**Comment by HAWinther** [comment]
Thanks Bartolomeo, I will upload a fix now. The floating-point type used from the grid-data is defined in FML::GRID::FloatType. This will be double when we use double-precision FFTs and float when we use single precision FFTs. Thus changing norm_poisson_equation to FML::GRID::FloatType(norm_poisson_equation) should work.

**Comment by BartolomeoF** [comment]
Hi Hans,

Thanks for your quick reply. I opened the issue as this is how I’ve got used to do for code development inside Euclid, but let me know if you prefer direct emails instead.

Thanks again,
Bartolomeo

On 8 Mar 2024, at 13:54, Hans A. Winther ***@***.***> wrote:

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>


Thanks Bartolomeo, I will upload a fix now. The floating-point value used from the grid-data is defined in FML::GRID::FloatType. This will be double when we use double-precision FFTs and float when we use single precision FFTs. Thus changing norm_poisson_equation to FML::GRID::FloatType(norm_poisson_equation) should work.

**Comment by HAWinther** [comment]
No this is great, much better way to do it than by email (for which I easily forget) :)
